"""Curated Phosphor icon catalog for days-since counters.

Each entry stays intentionally compact: the frontend uses the label and
keywords for search and name-aware suggestions, while storage validates the
stable icon name.
"""

from __future__ import annotations


_DEFINITIONS = [
    ("prohibit", "Stop", "no quit stop free avoid sober clean"),
    ("cigarette-slash", "Smoke free", "smoke smoking cigarette nicotine tobacco vape quit"),
    ("wine", "Wine", "alcohol wine drinking sober sobriety"),
    ("beer-bottle", "Beer", "alcohol beer drinking sober sobriety"),
    ("martini", "Drink", "alcohol cocktail drinking sober sobriety"),
    ("hamburger", "Fast food", "burger junk fast food diet eating"),
    ("pizza", "Pizza", "pizza junk fast food diet eating"),
    ("cookie", "Sugar", "cookie sugar sweets snack dessert"),
    ("cake", "Dessert", "cake birthday sugar sweets dessert"),
    ("coffee", "Coffee", "coffee caffeine espresso drink"),
    ("fork-knife", "Meals", "food meal eating diet nutrition"),
    ("cooking-pot", "Cooking", "cook cooking meal food kitchen"),
    ("carrot", "Vegetables", "vegetable healthy food diet carrot"),
    ("drop", "Water", "water hydration drink"),
    ("pill", "Medication", "medicine medication pill vitamins supplement"),
    ("first-aid-kit", "Health", "health medical doctor recovery first aid"),
    ("tooth", "Dental", "tooth teeth dental dentist brush floss"),
    ("eye", "Vision", "eye vision screen sight"),
    ("ear", "Hearing", "ear hearing listen"),
    ("heart", "Heart", "heart love health cardio"),
    ("heartbeat", "Wellbeing", "health heart pulse wellbeing recovery"),
    ("brain", "Mind", "brain mental focus mindfulness memory"),
    ("smiley", "Happy", "happy smile mood positivity"),
    ("bed", "Sleep", "bed sleep rest bedtime"),
    ("moon-stars", "Night", "sleep night bedtime evening"),
    ("sun", "Morning", "sun morning wake daylight"),
    ("shower", "Hygiene", "shower wash hygiene clean"),
    ("person-simple-walk", "Walking", "walk walking steps exercise movement"),
    ("person-simple-run", "Running", "run running cardio exercise jogging"),
    ("person-simple-bike", "Cycling", "bike bicycle cycling exercise"),
    ("person-simple-hike", "Hiking", "hike hiking trail outdoors exercise"),
    ("person-simple-swim", "Swimming", "swim swimming pool exercise"),
    ("person-simple-tai-chi", "Mindfulness", "yoga meditation stretch tai chi mindfulness"),
    ("barbell", "Strength", "gym workout weights lifting strength exercise"),
    ("bicycle", "Bicycle", "bike bicycle cycling commute"),
    ("swimming-pool", "Pool", "swim swimming pool water"),
    ("soccer-ball", "Football", "soccer football sport ball"),
    ("basketball", "Basketball", "basketball sport ball"),
    ("tennis-ball", "Tennis", "tennis racket sport ball"),
    ("football", "American football", "football sport ball"),
    ("medal", "Achievement", "medal achievement win success"),
    ("trophy", "Goal", "trophy goal win achievement streak"),
    ("book-open", "Reading", "read reading book study"),
    ("books", "Books", "books reading library study"),
    ("notebook", "Journal", "journal diary notes writing notebook"),
    ("pencil", "Writing", "write writing pencil journal"),
    ("graduation-cap", "Learning", "learn learning education school course study"),
    ("translate", "Language", "language learn translate vocabulary"),
    ("music-note", "Music", "music song practice instrument"),
    ("guitar", "Guitar", "guitar music instrument practice"),
    ("piano-keys", "Piano", "piano keyboard music instrument practice"),
    ("paint-brush", "Painting", "paint painting art creative"),
    ("palette", "Art", "art drawing paint creative"),
    ("camera", "Photography", "photo photography camera creative"),
    ("plant", "Plant", "plant garden gardening grow"),
    ("leaf", "Nature", "leaf nature eco outdoors"),
    ("tree", "Tree", "tree nature outdoors forest"),
    ("flower-lotus", "Meditation", "lotus meditation mindfulness calm"),
    ("recycle", "Recycle", "recycle environment sustainable"),
    ("trash", "Declutter", "trash clean declutter tidy"),
    ("broom", "Cleaning", "clean cleaning chores tidy broom"),
    ("house", "Home", "home house family chores"),
    ("key", "Key", "key access unlock"),
    ("lock", "Discipline", "lock secure privacy discipline"),
    ("shield-check", "Protected", "shield safe security protected"),
    ("briefcase", "Work", "work job career office business"),
    ("laptop", "Computer", "computer laptop work study screen"),
    ("code", "Coding", "code coding programming development"),
    ("terminal-window", "Development", "terminal code programming computer"),
    ("envelope", "Inbox", "email inbox message communication"),
    ("phone", "Calls", "phone call communication"),
    ("calendar-check", "Routine", "calendar routine schedule planning consistency"),
    ("clock", "Time", "clock time punctual schedule"),
    ("alarm", "Wake up", "alarm wake morning punctual"),
    ("timer", "Timer", "timer focus pomodoro time"),
    ("target", "Target", "target goal focus aim"),
    ("check-circle", "Complete", "check complete done success"),
    ("star", "Favorite", "star favorite success"),
    ("flag", "Milestone", "flag milestone goal finish"),
    ("lightning", "Energy", "energy lightning power action"),
    ("flame", "Streak", "flame fire streak motivation"),
    ("sparkle", "Self care", "sparkle clean self care improve"),
    ("users", "Friends", "friends people group social community"),
    ("user", "Personal", "person personal self individual"),
    ("baby", "Baby", "baby child parenting family"),
    ("dog", "Dog", "dog pet walk animal"),
    ("cat", "Cat", "cat pet animal"),
    ("paw-print", "Pet", "pet animal paw dog cat"),
    ("handshake", "Connection", "handshake agreement connection relationship"),
    ("hands-praying", "Gratitude", "pray prayer gratitude faith"),
    ("gift", "Gift", "gift giving generosity birthday"),
    ("car", "Driving", "car drive driving commute"),
    ("airplane", "Travel", "airplane flight travel trip"),
    ("suitcase", "Trip", "suitcase travel trip vacation"),
    ("map-pin", "Place", "place location visit map"),
    ("globe", "World", "world travel global internet"),
    ("mountains", "Outdoors", "mountain outdoors adventure hike"),
    ("umbrella", "Weather", "umbrella rain weather"),
    ("wallet", "Budget", "wallet money budget finance spending"),
    ("piggy-bank", "Saving", "save saving money finance piggy bank"),
    ("bank", "Finance", "bank finance money savings"),
    ("currency-dollar", "Money", "money dollar finance income"),
    ("credit-card", "Spending", "credit card spending shopping money debt"),
    ("shopping-cart", "Shopping", "shopping cart groceries spending"),
    ("shopping-bag", "Purchases", "shopping bag purchase spending"),
    ("device-mobile", "Phone", "phone mobile screen social media doomscrolling"),
    ("television", "Television", "tv television screen streaming"),
    ("game-controller", "Gaming", "game gaming controller console"),
    ("bell", "Reminder", "bell reminder notification"),
    ("hourglass", "Patience", "hourglass wait patience time"),
    ("stairs", "Progress", "stairs progress climb improve"),
    ("steps", "Steps", "steps progress walking"),
    ("footprints", "Journey", "footprints journey walk progress"),
    ("church", "Faith", "church faith religion worship"),
    ("peace", "Peace", "peace calm relax conflict"),
    ("flower", "Growth", "flower growth garden wellbeing"),
    ("tree-evergreen", "Consistency", "evergreen tree consistency nature"),
    ("cloud-sun", "Fresh air", "weather outdoors fresh air"),
    ("sun-horizon", "Sunrise", "sunrise morning early wake"),
    ("moon", "Rest", "moon night rest sleep"),
    ("heart-break", "Relationship", "breakup relationship heart love"),
    ("smiley-sad", "Mood", "sad mood emotion mental"),
    ("person-simple", "Activity", "person activity body movement"),
    ("check-square", "Habit", "check habit task routine done"),
    ("bookmark", "Remember", "bookmark remember save reading"),
    ("camera-plus", "Create", "camera photo create project"),
    ("microphone", "Speaking", "microphone speaking voice podcast"),
    ("headphones", "Listening", "headphones listen audio music"),
    ("wrench", "Repair", "repair fix maintain wrench"),
    ("hammer", "Build", "hammer build diy project"),
    ("paint-roller", "Renovation", "paint renovate home project"),
    ("calculator", "Numbers", "calculator math numbers budget"),
    ("chart-line-up", "Improvement", "chart growth improve progress business"),
    ("money", "Income", "money cash income finance"),
    ("receipt", "Expenses", "receipt expense spending budget"),
    ("hand-heart", "Kindness", "kindness charity care volunteer love"),
    ("confetti", "Celebrate", "celebrate party success confetti"),
    ("calendar-heart", "Anniversary", "calendar anniversary date love"),
    ("map-trifold", "Explore", "map explore travel adventure"),
    ("compass", "Direction", "compass direction purpose explore"),
]

COUNTER_ICON_CATALOG = [
    {"name": name, "label": label, "keywords": keywords.split()}
    for name, label, keywords in _DEFINITIONS
]
COUNTER_ICONS = [entry["name"] for entry in COUNTER_ICON_CATALOG]
